spring: 
  profiles: 
    active: 
    - dev
---
spring: 
  profiles: dev
    application: ddd
      name: microservicecloud-config-atguigu-dev
---
spring: 
  profiles: test
    application: 
    	name: microservicecloud-config-atguigu-test
